[package]
name = "rawsock_ndk"
version = "0.1.0"
authors = ["djdisodo <djdisodo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = "0.17"
pnet = "0.26"

[lib]
crate_type = ["cdylib"]

